### ISSUE TITLE
Data validation

### ISSUE THREAD

**Issue by vggscqq** [h1w/opencyb-website#1]
You might add data validation to make sure everything will work right

**Comment by h1w** [comment]
> You might add data validation to make sure everything will work right

I am currently working with validation. Almost ready.

**Comment by h1w** [comment]
> You might add data validation to make sure everything will work right

Done.
You can check in [commit](https://github.com/h1w/opencyb-website/commit/fdb5dc55016a0d1b2008afc8ed3fcc1da51df707)

**Comment by vggscqq** [comment]
Скорострел Вадимка
