### ISSUE TITLE
Secrets disclosure in config files.

### ISSUE THREAD

**Issue by vggscqq** [h1w/opencyb-website#2]
Commit  c803a0a pushed raw session_key in ` opencyb-website/configs/apiserver.toml `

**Comment by h1w** [comment]
> Commit [c803a0a](https://github.com/h1w/opencyb-website/commit/c803a0a4fbac377ade6bec03c4a5c439549a8a28) pushed raw session_key in `opencyb-website/configs/apiserver.toml`

This is a test key. I just tapped on the keyboard random characters.
Thank you for your attentiveness.
